---
- name: Install nginx
  hosts: ubuntu
  become: true  # Elevates to root
  tasks:
    - name: Ensure python3-apt is installed
      apt:
         name: python3-apt
         state: present
    - name: Install nginx
      apt:
         name: nginx
         state: present
    - name: Install apache2
      apt:
         name: apache2
         state: present
- name: Software Install
  hosts: al
  become: true
  tasks:
    - name: Install nginx service
      yum:
          name: nginx
          state: present
    - name: Install nginx
      yum:
          name: nginx
          state: present
    - name: Ensure python3-dnf is installed
      dnf:
          name: python3-dnf
          state: present
      yum:
          name: httpd
          state: present
